#!/bin/bash

# Demo script for wesleyscholl.github.io - Personal portfolio site

set -e

echo "=========================================="
echo "  🌐 Wesley Scholl - Portfolio Site"
echo "  Professional Developer Portfolio"
echo "=========================================="
echo ""

echo "🔍 Site Information:"
if [ -f "_config.yml" ]; then
    echo "   ✅ Jekyll site detected"
    echo "   • GitHub Pages deployment"
    echo "   • Custom layouts and themes"
    echo "   • Responsive design"
else
    echo "   ⚠️  _config.yml not found"
fi

echo ""
echo "✨ Portfolio Sections:"
echo ""
echo "   👨‍💻 About"
echo "      • Professional bio"
echo "      • Technical expertise"
echo "      • Career highlights"
echo "      • Contact information"
echo ""
echo "   🚀 Projects"
echo "      • 29+ open-source repositories"
echo "      • Production applications"
echo "      • AI/ML systems"
echo "      • DevOps tools"
echo ""
echo "   🏆 Achievements"
echo "      • Professional certifications"
echo "      • Technical contributions"
echo "      • Community involvement"
echo "      • Speaking engagements"
echo ""
echo "   📝 Blog"
echo "      • Technical articles"
echo "      • Tutorials"
echo "      • Best practices"
echo "      • Industry insights"
echo ""

echo "🎨 Design Features:"
echo "   • Modern responsive layout"
echo "   • Dark/light mode support"
echo "   • Smooth animations"
echo "   • Fast page loads"
echo "   • SEO optimized"
echo ""

echo "🚀 Local Development:"
echo ""
echo "   1. Install Jekyll:"
echo "      gem install bundler jekyll"
echo ""
echo "   2. Install dependencies:"
echo "      bundle install"
echo ""
echo "   3. Run locally:"
echo "      bundle exec jekyll serve"
echo ""
echo "   4. View at:"
echo "      http://localhost:4000"
echo ""

echo "📊 Portfolio Metrics:"
echo "   • GitHub Repos: 100+"
echo "   • Total Stars: 500+"
echo "   • Languages: 10+"
echo "   • Years Experience: 10+"
echo "   • Certifications: 5+"
echo ""

echo "🔗 Links:"
echo "   • Website: https://wesleyscholl.github.io"
echo "   • GitHub: https://github.com/wesleyscholl"
echo "   • LinkedIn: linkedin.com/in/wesleyscholl"
echo ""

echo "=========================================="
echo "  Repository: github.com/wesleyscholl/wesleyscholl.github.io"
echo "  Type: Jekyll Portfolio | GitHub Pages"
echo "=========================================="
echo ""
